spring.application.name=trip-service
spring.cloud.config.profile=dev

# Importation de la configuration depuis le Config Server
# On utilise le nom du service docker 'config-server'
spring.config.import=optional:configserver:http://config-server:8888

# On autorise l'écrasement des beans au cas où
spring.main.allow-bean-definition-overriding=true