spring.application.name=trip-service

spring.cloud.config.profile=dev

# Importation de la configuration depuis le Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Utilisation des variables dynamiques (définies dans le repo Git)
server.port=${trip-service.uriport}

# Configuration de la base de données (trips_db)
spring.datasource.url=${trip-service.datasource-url}
spring.datasource.username=${trip-service.username}
spring.datasource.password=${trip-service.password}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${trip-service.hibernate-ddl-auto}
spring.jpa.show-sql=${trip-service.showsql}

# Eureka Registry
eureka.client.service-url.defaultZone=${trip-service.urlregistry}

# Activation de Feign et Circuit Breaker
spring.cloud.openfeign.circuitbreaker.enabled=true
spring.main.allow-bean-definition-overriding=true


# Désactive le check de santé qui fait passer le service en "DOWN"
management.health.rabbit.enabled=false

# Désactive les tentatives de reconnexion automatique
spring.rabbitmq.template.retry.enabled=false

# On donne 10 secondes aux services pour répondre
resilience4j.timelimiter.instances.default.timeout-duration=10s
# On autorise plus de temps pour l'appel au Billing
resilience4j.timelimiter.instances.billing-service.timeout-duration=10s

# Configuration spécifique pour User et Billing (les noms exacts de tes clients)
resilience4j.timelimiter.instances.UserServiceClientvalidatePassLong.timeout-duration=10s
resilience4j.timelimiter.instances.BillingServiceClientdebitDebitRequest.timeout-duration=10s